version: "3.5"

services:
  postgres:
    image: postgres:14-alpine
    container_name: my-postgres-on-docker
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: